apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-vite-app
  template:
    metadata:
      labels:
        app: react-vite-app
    spec:
      containers:
      - name: react-vite-app
        image: 076510357639.dkr.ecr.ap-south-1.amazonaws.com/react-vite-app:latest
        ports:
        - containerPort: 80
